function [ColwellMat,ColwellBounds,CollwellLabels,Opt]=mhit_get_colwellMat(discharge,month,day,Opt)
validateattributes(discharge,{'single','double'},{'column'});
validateattributes(month,{'int16','int32','int64','uint16','uint32','uint64','single','double'},{'column'});
validateattributes(day,{'int16','int32','int64','uint16','uint32','uint64','single','double'},{'column'});

%% Checking Options
if (nargin<4 || isempty(Opt))
  [~,Opt]=mhit_get_MA1(discharge);
else
  if (~isfield(Opt,'meanDischarge') || isempty(Opt.meanDischarge))
    [~,Opt]=mhit_get_MA1(discharge,Opt);
  end
end

%%
if (Opt.meanDischarge<1)
  ColwellBounds=(([0.10; ...
                 0.25; ...
                 0.50; ...
                 0.75; ...
                 1.00; ...
                 1.25; ...
                 1.50; ...
                 1.75; ...
                 2.00; ...
                 2.25]-1)*-0.9+1)*log10(Opt.meanDischarge+eps);
else
  ColwellBounds=[0.10; ...
                 0.25; ...
                 0.50; ...
                 0.75; ...
                 1.00; ...
                 1.25; ...
                 1.50; ...
                 1.75; ...
                 2.00; ...
                 2.25]*log10(Opt.meanDischarge);
end
Opt.ColwellBounds=ColwellBounds;
[ColwellMat,~,~,CollwellLabels] = crosstab(imquantize(log10(discharge+eps),ColwellBounds), ...
                                      num2str([month, day],'%0.2d_%0.2d\n'));

Feb29Mask = strcmpi(CollwellLabels(:,2),'02_29');

ColwellMat= ColwellMat(:,~Feb29Mask);

Opt.ColwellMat=ColwellMat;
Opt.CollwellLabels=CollwellLabels;

end
